import re
import logging
from src.chat_api.api.v1.schemas import Source, ChatResponse

logger = logging.getLogger(__name__)

BLOCKED_PATTERNS = {
    "classification": re.compile(r"(classify|categorize|tag)\s+(this|the\s+(text|document|content))", re.IGNORECASE),
    "content_generation": re.compile(r"(write|compose|draft|generate|create)\s+(an?\s+)?(email|essay|article|poem|story|report|letter)", re.IGNORECASE),
    "summarization": re.compile(r"(summarize|summary|tldr|tl;dr|gist)\s+(of\s+)?(this|the\s+(text|document|article))", re.IGNORECASE),
    "pii": re.compile(r"(ssn|social security|credit card|passport|driver.?s license)\s+(number|info|details)", re.IGNORECASE),
}

MAX_COMPLEXITY_SCORE = 3

FALLBACK_REPLY = "I couldn't find relevant information to answer that question."


class GuardrailService:
    def check_blocked_question(self, message: str) -> str | None:
        for reason, pattern in BLOCKED_PATTERNS.items():
            if pattern.search(message):
                logger.info("Blocked question detected: %s (message: %.50s)", reason, message)
                return reason
        return None

    def assess_complexity(self, message: str) -> int:
        score = 0
        entity_keywords = {"how many", "count", "list", "show", "what", "which", "find", "search"}
        question_marks = message.count("?")
        score += min(question_marks, 3)
        words = set(w.lower() for w in message.split())
        score += sum(1 for kw in entity_keywords if any(kw in w for w in words))
        complexity = min(score, 5)
        logger.info("Query complexity score: %d (message: %.50s)", complexity, message)
        return complexity

    def check_blocked_question_type(self, message: str, tenant_id: str) -> str | None:
        cross_tenant = re.search(rf"(?!\b{re.escape(tenant_id)}\b)\btenant_\w+\b", message, re.IGNORECASE) if tenant_id else False
        if cross_tenant:
            logger.info("Cross-tenant query detected")
            return "cross_tenant"
        return self.check_blocked_question(message)

    def enforce_sources(self, reply: str, sources: list[Source]) -> tuple[str, list[Source]]:
        if not sources:
            logger.warning("Guardrail: empty sources detected, returning fallback reply")
            return FALLBACK_REPLY, []
        return reply, sources

    def inject_disclaimer(self) -> str:
        return "This answer was generated by AI and may contain errors. Verify important information against source documents."
