import pytest
from src.chat_api.services.guardrails import GuardrailService
from src.chat_api.api.v1.schemas import Source

pytestmark = [pytest.mark.verification, pytest.mark.asyncio]


class TestGuardrails:
    def setup_method(self):
        self.guardrails = GuardrailService()

    def test_20_empty_sources_rejected(self):
        reply = "Here is some information"
        result_reply, result_sources = self.guardrails.enforce_sources(reply, [])
        assert result_reply == "I couldn't find relevant information to answer that question."
        assert result_sources == []

    def test_20_non_empty_sources_passes(self):
        reply = "Here is some information"
        sources = [Source(source_type="sql", value="test", relevance_score=1.0)]
        result_reply, result_sources = self.guardrails.enforce_sources(reply, sources)
        assert result_reply == reply
        assert result_sources == sources

    def test_21_classification_blocked(self):
        reason = self.guardrails.check_blocked_question("Classify this text document")
        assert reason is not None

    def test_21_content_generation_blocked(self):
        reason = self.guardrails.check_blocked_question("Write an email to the team")
        assert reason is not None

    def test_21_summarization_blocked(self):
        reason = self.guardrails.check_blocked_question("Summarize this article for me")
        assert reason is not None

    def test_21_pii_query_blocked(self):
        reason = self.guardrails.check_blocked_question("Show me social security numbers")
        assert reason is not None

    def test_21_normal_query_not_blocked(self):
        reason = self.guardrails.check_blocked_question("How many organizations did we extract?")
        assert reason is None

    def test_22_complexity_low_passes(self):
        score = self.guardrails.assess_complexity("How many entities?")
        assert score <= 3

    def test_22_complexity_high_rejected(self):
        score = self.guardrails.assess_complexity("How many ORG entities? What about PERSON? And LOC? Show me documents too?")
        assert score > 3 or self.guardrails.assess_complexity("What? Where? When? Who? Why?") > 3

    def test_23_disclaimer_injected(self):
        disclaimer = self.guardrails.inject_disclaimer()
        assert "generated by AI" in disclaimer
        assert "may contain errors" in disclaimer

    def test_cross_tenant_detected(self):
        reason = self.guardrails.check_blocked_question_type("How is tenant_abc doing?", tenant_id="tenant_xyz")
        assert reason is not None

    def test_same_tenant_not_blocked(self):
        reason = self.guardrails.check_blocked_question_type("How is our data?", tenant_id="tenant_xyz")
        assert reason is None
