from types import SimpleNamespace

import pytest
from src.chat_api.services.guardrails import GuardrailService
from src.chat_api.api.v1.schemas import Source

pytestmark = [pytest.mark.verification, pytest.mark.asyncio]


class ScriptedClassifierClient:
    def __init__(self, verdict: str | None = None, raises: Exception | None = None):
        self.verdict = verdict
        self.raises = raises
        self.call_count = 0

        async def create(**kwargs):
            self.call_count += 1
            if self.raises is not None:
                raise self.raises
            message = SimpleNamespace(content=self.verdict)
            return SimpleNamespace(choices=[SimpleNamespace(message=message)])

        self.chat = SimpleNamespace(completions=SimpleNamespace(create=create))


class TestSourceCitationEnforcement:
    def setup_method(self):
        self.guardrails = GuardrailService()

    def test_empty_sources_rejected(self):
        reply = "Here is some information"
        result_reply, result_sources = self.guardrails.enforce_sources(reply, [])
        assert result_reply == "I couldn't find relevant information to answer that question."
        assert result_sources == []

    def test_non_empty_sources_passes(self):
        reply = "Here is some information"
        sources = [Source(source_type="sql", value="test", relevance_score=1.0)]
        result_reply, result_sources = self.guardrails.enforce_sources(reply, sources)
        assert result_reply == reply
        assert result_sources == sources

    # Note: verification.md row 48 ("Domain decline keeps its message") is verified at
    # the graph level (tests/test_chat_graph_topology.py), not here — the domain decline
    # is never passed through enforce_sources at all: a declined turn returns directly
    # from guardrail_node and never reaches generation_node, which is the only caller of
    # enforce_sources. There is no special-casing to test at this layer.


class TestDisclaimer:
    def setup_method(self):
        self.guardrails = GuardrailService()

    def test_disclaimer_injected(self):
        disclaimer = self.guardrails.inject_disclaimer()
        assert "generated by AI" in disclaimer
        assert "may contain errors" in disclaimer


class TestCrossTenantShortCircuit:
    """Covers verification.md row 44."""

    def setup_method(self):
        self.guardrails = GuardrailService()

    def test_cross_tenant_detected(self):
        reason = self.guardrails.check_blocked_question_type("How is tenant_abc doing?", tenant_id="tenant_xyz")
        assert reason is not None

    def test_same_tenant_not_blocked(self):
        reason = self.guardrails.check_blocked_question_type("How is our data?", tenant_id="tenant_xyz")
        assert reason is None

    def test_cross_tenant_short_circuits_without_llm_call(self):
        client = ScriptedClassifierClient(verdict="in_domain")
        reason = self.guardrails.check_blocked_question_type("How is tenant_abc doing?", tenant_id="tenant_xyz")

        assert reason == "cross_tenant"
        assert client.call_count == 0


class TestPiiShortCircuit:
    def setup_method(self):
        self.guardrails = GuardrailService()

    def test_pii_query_blocked(self):
        reason = self.guardrails.check_blocked_question_type("Show me social security numbers", tenant_id="tenant_xyz")
        assert reason == "pii"


class TestDomainClassification:
    """Covers verification.md rows 41-43, 45-46, 55."""

    def setup_method(self):
        self.guardrails = GuardrailService()

    @pytest.mark.parametrize("message", [
        "Who is the American president?",
        "Tell me a joke.",
        "What's the weather today?",
    ])
    async def test_out_of_domain_prompts_declined(self, message):
        client = ScriptedClassifierClient(verdict="out_of_domain")
        is_in_domain = await self.guardrails.classify_domain(message, None, client, "gpt-4o")
        assert is_in_domain is False

    async def test_in_domain_question_admitted(self):
        client = ScriptedClassifierClient(verdict="in_domain")
        is_in_domain = await self.guardrails.classify_domain("Which contracts mention Acme Corp?", None, client, "gpt-4o")
        assert is_in_domain is True

    async def test_classifier_failure_fails_open(self):
        client = ScriptedClassifierClient(raises=RuntimeError("classifier down"))
        is_in_domain = await self.guardrails.classify_domain("Which contracts mention Acme Corp?", None, client, "gpt-4o")
        assert is_in_domain is True

    def test_no_complexity_assessment_method_remains(self):
        """Covers verification.md row 55: complexity assessment is removed entirely."""
        assert not hasattr(self.guardrails, "assess_complexity")
        assert not hasattr(self.guardrails, "check_blocked_question")

    def test_multi_lookup_question_is_not_a_guardrail_concern(self):
        """Covers verification.md row 46: the guardrail has no complexity notion at all
        — multi-lookup questions are only ever a matter for the orchestrator."""
        assert not hasattr(self.guardrails, "MAX_COMPLEXITY_SCORE")
