from typing import Literal
from pydantic import BaseModel, Field, field_validator, model_validator

AnswerKind = Literal["answer", "clarification", "guardrail_blocked", "out_of_domain"]
Rating = Literal["up", "down"]


class AttachmentOut(BaseModel):
    id: str
    filename: str
    mime_type: str | None = None
    file_size_bytes: int | None = None
    conversation_id: str | None = None
    created_at: str


class ChatRequest(BaseModel):
    """The turn itself. Attachment *content* never appears here — an attachment-bearing
    turn is sent as `multipart/form-data` and its files arrive as upload parts, because
    a filename and a byte count cannot be retrieved against (ADR-014, CAP-6)."""

    message: str = Field(..., min_length=1, max_length=4000)
    conversation_id: str | None = None


class Source(BaseModel):
    source_type: str
    document_id: str | None = None
    chunk_index: int | None = None
    chunk_text: str | None = None
    relevance_score: float | None = None
    entity_type: str | None = None
    value: str | None = None
    confidence: float | None = None
    page_number: int | None = None
    model_version: str | None = None


class Citation(BaseModel):
    document_name: str | None = None
    document_id: str | None = None
    entity_type: str | None = None
    entity_value: str | None = None
    confidence: float | None = None
    relevance_score: float | None = None
    context_snippet: str | None = None
    page_number: int | None = None
    source_type: str = "citation"
    model_version: str | None = None


class CandidateEntity(BaseModel):
    document_id: str
    name: str
    organization: str | None = None
    experience: str | None = None
    skills: list[str] = []
    filename: str | None = None


class PendingClarification(BaseModel):
    mention: str
    candidates: list[CandidateEntity]


RetrievalOutcome = Literal["not_attempted", "ok", "empty", "failed", "skipped"]


class RetrievalStatusEntry(BaseModel):
    capability_name: str
    outcome: RetrievalOutcome
    error: str | None = None
    result_count: int = 0
    reason: str | None = None
    recovery: bool = False


class RetrievalStatusOut(BaseModel):
    """Per-capability retrieval outcome for the turn. Additive: a client that ignores
    it observes no change in any other field."""

    entries: list[RetrievalStatusEntry] = []
    planning_degraded: bool = False
    stop_reason: str | None = None


class ExportAvailability(BaseModel):
    """Describes whether a structured-result snapshot is downloadable for this
    turn — metadata only, never the row data itself (chat-export capability)."""

    message_id: str
    row_count: int
    formats: list[str] = ["csv", "xlsx"]


ChartType = Literal["bar", "line", "pie"]


class ChartSeries(BaseModel):
    name: str
    data: list[float]


class ChartPayload(BaseModel):
    chart_type: ChartType
    title: str
    x_label: str | None = None
    y_label: str | None = None
    categories: list[str] = Field(..., min_length=1)
    series: list[ChartSeries] = Field(..., min_length=1)

    @model_validator(mode="after")
    def series_align_with_categories(self):
        width = len(self.categories)
        for entry in self.series:
            if len(entry.data) != width:
                raise ValueError(
                    f"series '{entry.name}' has {len(entry.data)} values "
                    f"but there are {width} categories"
                )
        return self


class ChatResponse(BaseModel):
    reply: str
    sources: list[Source | Citation]
    conversation_id: str | None = None
    disclaimer: str = "This answer was generated by AI and may contain errors. Verify important information against source documents."
    pending_clarification: PendingClarification | None = None
    message_id: str | None = None
    answer_kind: AnswerKind | None = None
    model_version: str | None = None
    retrieval_status: RetrievalStatusOut | None = None
    export: ExportAvailability | None = None
    chart: ChartPayload | None = None


class ConversationSummary(BaseModel):
    id: str
    title: str | None
    created_at: str
    message_count: int


class ConversationRenameRequest(BaseModel):
    title: str = Field(..., min_length=1, max_length=100)

    @field_validator("title")
    @classmethod
    def title_must_not_be_blank(cls, value: str) -> str:
        stripped = value.strip()
        if not stripped:
            raise ValueError("title must not be blank")
        return stripped


class ConversationRenameResponse(BaseModel):
    id: str
    title: str


class FeedbackCreate(BaseModel):
    rating: Rating


class FeedbackOut(BaseModel):
    message_id: str
    rating: Rating
    created_at: str


class MessageAttachment(BaseModel):
    id: str
    filename: str
    mime_type: str | None = None
    file_size_bytes: int | None = None


class MessageResponse(BaseModel):
    id: str
    role: str
    content: str
    sources: list[Source | Citation] | None = None
    created_at: str
    answer_kind: AnswerKind | None = None
    model_version: str | None = None
    feedback: FeedbackOut | None = None
    export: ExportAvailability | None = None
    chart: ChartPayload | None = None
    # The files the user attached on this turn. Metadata only, recorded on the message
    # so the thread still shows them after a reload or a conversation switch.
    attachments: list[MessageAttachment] | None = None


class ConversationDetail(BaseModel):
    id: str
    title: str | None
    created_at: str
    messages: list[MessageResponse]
    attachments: list[AttachmentOut] = Field(default_factory=list)


class ConversationCreateResponse(BaseModel):
    id: str
    title: str | None = None
    created_at: str


class WidgetKeyResponse(BaseModel):
    id: str
    key_prefix: str
    created_at: str
    last_used_at: str | None = None


class WidgetKeyCreateResponse(BaseModel):
    id: str
    raw_key: str
    key_prefix: str


class WidgetChatRequest(BaseModel):
    message: str = Field(..., min_length=1, max_length=4000)


class WidgetChatResponse(BaseModel):
    reply: str
    sources: list[Source]
    disclaimer: str = "This answer was generated by AI and may contain errors. Verify important information against source documents."
