from pydantic import BaseModel, Field


class ChatRequest(BaseModel):
    message: str = Field(..., min_length=1, max_length=4000)
    conversation_id: str | None = None


class Source(BaseModel):
    source_type: str
    document_id: str | None = None
    chunk_index: int | None = None
    chunk_text: str | None = None
    relevance_score: float | None = None
    entity_type: str | None = None
    value: str | None = None
    confidence: float | None = None


class Citation(BaseModel):
    document_name: str | None = None
    document_id: str | None = None
    entity_type: str | None = None
    entity_value: str | None = None
    confidence: float | None = None
    context_snippet: str | None = None
    page_number: int | None = None
    source_type: str = "citation"


class ChatResponse(BaseModel):
    reply: str
    sources: list[Source | Citation]
    conversation_id: str | None = None
    disclaimer: str = "This answer was generated by AI and may contain errors. Verify important information against source documents."


class ConversationSummary(BaseModel):
    id: str
    title: str | None
    created_at: str
    message_count: int


class MessageResponse(BaseModel):
    id: str
    role: str
    content: str
    sources: list[Source | Citation] | None = None
    created_at: str


class ConversationDetail(BaseModel):
    id: str
    title: str | None
    created_at: str
    messages: list[MessageResponse]


class ConversationCreateResponse(BaseModel):
    id: str
    title: str | None = None
    created_at: str


class WidgetKeyResponse(BaseModel):
    id: str
    key_prefix: str
    created_at: str
    last_used_at: str | None = None


class WidgetKeyCreateResponse(BaseModel):
    id: str
    raw_key: str
    key_prefix: str


class WidgetChatRequest(BaseModel):
    message: str = Field(..., min_length=1, max_length=4000)


class WidgetChatResponse(BaseModel):
    reply: str
    sources: list[Source]
    disclaimer: str = "This answer was generated by AI and may contain errors. Verify important information against source documents."
