apiVersion: v1
kind: Service
metadata:
  name: mlflow-tracking-server
  labels:
    app: mlflow
    component: tracking
spec:
  ports:
    - port: 5000
      targetPort: 5000
      name: http
  selector:
    app: mlflow
    component: tracking
  type: ClusterIP
